### ISSUE TITLE
Implement framework properties

### ISSUE THREAD

**Issue by jeffdiclemente** [jeffdiclemente/CppMicroServices#5]
Framework properties are needed for CppMicroServices settings which used to be in the ModuleSettings class.

The initial framework properties we are concerned with are for threading, logging and Framework persistent storage location. For each of these properties, the following needs to be determined:
- What does the property mean to the client?
- What is the property's purpose?
- What is the property's default value (if the client doesn't override it)? 

**NOTE:** To avoid any trademark issues, DO NOT use "org.osgi" for the property name, instead start them with "org.cppmicroservices"
#### Requirements
1. A framework property for threading, logging, and the Framework's persistent storage are required.
2. There are accessor functions in the Framework class for each property name (similar to what usModule.cpp does for bundle meta-data).
3. There is a default value for each framework property.
4. Start all property names with "org.cppmicroservices"

**Comment by saschazelzer** [comment]
A note for 2.: function local static variables were required for the property names because of static initialization ordering problems within the CppMicroServices library. Since we are moving away from static initialization, the framework properties (as well as the meta data properties) can possibly be implemented as static variables instead of functions.

Overall, it does look good me.
